version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_nest_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/tasks_nest_db
    ports:
      - "3000:3000"
    depends_on:
      - db
